version: 0.0
os: linuxfiles:
  - source: /
    destination: /var/local/bg-hub
hooks:
  ApplicationStop:
    - location: aws-lifecycle/application-stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws-lifecycle/after-install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: aws-lifecycle/application-start.sh
      timeout: 300
      runas: root