version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/default.conf
      - /var/local/bg-hub/static:/var/local/bg-hub/static
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
    networks:
      - cupnet

  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cupnet

  adminer:
    image: adminer
    restart: always
    networks:
      - cupnet

volumes:
  pg-data:

networks:
  cupnet: