version: "3"

services:

  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cupnet

  bg-hub:
    build:
      context: ./backend
    networks:
      - cupnet
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

  bg-web:
    build:
      context: ./web
      args:
        configuration: ""
    networks:
      - cupnet
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
    depends_on:
      - bg-hub


volumes:
  pg-data:

networks:
  cupnet: