version: "3"

services:

  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cupnet

  # adminer:
  #   image: adminer:4.6.3
  #   restart: always
  #   volumes:
  #     - ./adminer/adminer.php:/var/www/html/adminer.php
  #   networks:
  #     - cupnet

  bg-hub:
    build:
      context: ./backend
    networks:
      - cupnet
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  bg-web:
    build:
      context: ./web
    networks:
      - cupnet
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
    depends_on:
      - bg-hub


volumes:
  pg-data:

networks:
  cupnet: